name: Release · Buildah Image

"on":
  push:
    branches: [main]
    paths-ignore:
      - .github/**
  workflow_dispatch:

run-name: "CI · ${{ github.event_name }} · ${{ github.sha }}"

concurrency:
  group: release-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  init:
    uses: grootan-devops/github-ci-library/.github/workflows/init.yml@dev
    secrets: inherit
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      ignore-docker: "false"
      ignore-chart: "true"

  lint:
    uses: grootan-devops/github-ci-library/.github/workflows/lint.yml@dev
    secrets: inherit
    permissions:
      contents: read
    with:
      lint-md-files: "*.md"

  trivy-cache:
    uses: grootan-devops/github-ci-library/.github/workflows/trivy-cache.yml@dev
    secrets: inherit
    permissions:
      contents: read
      actions: write
    with:
      enable-java-db: false

  check:
    needs: init
    uses: grootan-devops/github-ci-library/.github/workflows/check.yml@dev
    secrets: inherit
    permissions:
      contents: read
    with:
      tag: ${{ needs.init.outputs.tag }}
      image-tag: ${{ needs.init.outputs.image-tag }}
      image-repository: ${{ needs.init.outputs.image-repository }}
      allow-unstable-library-refs: true

  image-scan:
    needs: [init, trivy-cache]
    uses: grootan-devops/github-ci-library/.github/workflows/scan.yml@dev
    secrets: inherit
    permissions:
      contents: read
      checks: write
    with:
      scan-type: image
      image-repository: ${{ needs.init.outputs.image-push-repository }}
      target-version: ${{ needs.init.outputs.candidate-image-tag }}
      fail-on-warnings: true

  promote:
    needs: [init, check, image-scan]
    uses: grootan-devops/github-ci-library/.github/workflows/buildah.yml@dev
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      is-release: true
      require-scan: true
      scan-result: ${{ needs.image-scan.result }}
      image-tag: ${{ needs.init.outputs.image-tag }}
      image-repository: ${{ needs.init.outputs.image-repository }}
      image-dev-repository: ${{ needs.init.outputs.image-dev-repository }}
      release-tag: ${{ needs.init.outputs.tag }}
      candidate-tag: ${{ needs.init.outputs.candidate-image-tag }}

  github-release:
    needs: [init, promote]
    uses: grootan-devops/github-ci-library/.github/workflows/release.yml@dev
    secrets: inherit
    permissions:
      contents: write
      actions: read
    with:
      tag: ${{ needs.init.outputs.tag }}
      upstream-run-id: ${{ needs.init.outputs.upstream-run-id }}
