name: Scan · Full Git History Secrets

on:
  workflow_dispatch:

run-name: "CI · ${{ github.event_name }} · ${{ github.sha }}"

concurrency:
  group: secret-scan-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  secret-scan:
    uses: grootan-devops/github-ci-library/.github/workflows/secret-scanning.yml@dev
    secrets: inherit
    permissions:
      contents: read
    with:
      full-history: true
